#启动指定环境
spring:
  profiles:
    active: ${profile.active}
---
#开发环境
spring:
  profiles: dev
server:
  port: 80
---
#生产环境
spring:
  profiles: pro
server:
  port: 81
---
#测试环境
spring:
  profiles: test
server:
  port: 82
---
lesson: SpringBoot

enterprise:
  name: it
  age: 16
  tel: 4006184000
  subject:
    - Java
    - 前端
    - 大数据