#启动指定环境
spring:
  profiles:
    active: pro
---
#开发环境
spring:
  profiles: dev
server:
  port: 90
---
#生产环境
spring:
  profiles: pro
server:
  port: 91
---
#测试环境
spring:
  profiles: test
server:
  port: 92
---
lesson: SpringBoot

enterprise:
  name: itcast
  age: 16
  tel: 4006184000
  subject:
    - Java
    - 前端
    - 大数据